use_frameworks!

target 'iOSAppFramework_Example' do
    pod 'iOSAppFramework', :path => '../', :subspecs => ['iOS']
    pod 'iOSAppFramework', :path => '../', :subspecs => ['ThirdParty']

  #target 'iOSAppFramework_Tests' do
   # inherit! :search_paths

    #pod 'Specta'
  #pod 'Expecta'
  #pod 'FBSnapshotTestCase'
  #pod 'Expecta+Snapshots'
  #end
end
